### ISSUE TITLE
Do we need a chat room?

### ISSUE THREAD

**Issue by daleharvey** [yes-labs/projects#2]
Could help boost collaboration but also is more work, mostly guaging interest, we can start our own or hop on to an existing place

**Comment by affix** [comment]
A Discord server would satisfy this, and could be a useful place to discuss things

**Comment by daleharvey** [comment]
Yup thats a possibility, in the mean time however hanging around on the #politics channel in http://links.devtech.scot/slack if people fancy joining that

**Comment by daleharvey** [comment]
And done - http://indy.chat
